// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./db_types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable()
);

export const businessesRowSchema = z.object({
  city: z.string(),
  created_at: z.string(),
  gps_lat: z.number().nullable(),
  gps_long: z.number().nullable(),
  id: z.number(),
  name: z.string(),
  region: z.string(),
  street: z.string().nullable(),
  type: z.string(),
  website: z.string().nullable(),
  zipcode: z.string(),
});

export const businessesInsertSchema = z.object({
  city: z.string().min(2).max(25),
  gps_lat: z.number().optional(),
  gps_long: z.number().optional(),
  name: z.string().min(2).max(50),
  region: z.string().min(2).max(25),
  street: z.string().min(2).max(50),
  type: z.string().min(2).max(25),
  website: z.string().url().or(z.literal('')),
  zipcode: z.string().min(5).max(5),
});

export const businessesUpdateSchema = z.object({
  city: z.string().optional(),
  created_at: z.string().optional(),
  gps_lat: z.number().optional().nullable(),
  gps_long: z.number().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
  region: z.string().optional(),
  street: z.string().optional().nullable(),
  type: z.string().optional(),
  website: z.string().optional().nullable(),
  zipcode: z.string().optional(),
});

export const dealsRowSchema = z.object({
  business: z.number(),
  category: z.string().nullable(),
  created_at: z.string(),
  day: z.string().nullable(),
  description: z.string(),
  id: z.number(),
  time_end: z.string().nullable(),
  time_start: z.string().nullable(),
  type: z.string(),
});

export const dealsInsertSchema = z.object({
  business: z.string().min(1),
  category: z.string().min(1),
  day: z.string().min(1),
  description: z.string().min(3),
  time_end: z.string().optional().nullable(),
  time_start: z.string().optional().nullable(),
  type: z.string().min(1),
});

export const dealsUpdateSchema = z.object({
  business: z.number().optional(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  day: z.string().optional().nullable(),
  description: z.string().optional(),
  id: z.number().optional(),
  time_end: z.string().optional().nullable(),
  time_start: z.string().optional().nullable(),
  type: z.string().optional(),
});

export const profilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  updated_at: z.string().nullable(),
  username: z.string().nullable(),
  website: z.string().nullable(),
});

export const profilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const profilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});
